### ISSUE TITLE
Improve Apply for Job Form

### ISSUE THREAD

**Issue by rtewari056** [arpanaditya/BabyShop#10]
### Improve the from by adding additional styling and arrange the input fields in the middle of the form

![Screenshot 2022-10-17 102356](https://user-images.githubusercontent.com/75976169/196092344-d51ba7ee-af94-46b2-be4a-cfa5a5f0f344.png)

**Comment by arpanaditya** [comment]
Hello @rtewari056 :wave: sure, go for it. Would love to see your skills. :+1:
