### ISSUE TITLE
Improve Login Form 

### ISSUE THREAD

**Issue by Mahich123** [arpanaditya/BabyShop#12]
I would like to improve the current login from . Can  you assign me  ...
![image](https://user-images.githubusercontent.com/69717681/197290453-209d9341-2a91-447f-aa65-94ede20b681c.png)

**Comment by arpanaditya** [comment]
Hey @Mahich123 , sure I'd love to see your contributions. But before that, could you please tell me what changes you're planning to implement? :+1:

**Comment by Mahich123** [comment]
@arpanaditya  I want to align those text's and design that container

**Comment by Mahich123** [comment]
Made pr you can check the updates
